# Generated by Django 4.0.5 on 2022-06-14 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'обьект',
                'verbose_name_plural': 'обьект',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.object')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='objects',
            field=models.ManyToManyField(related_name='objects', through='articles.Relationship', to='articles.article'),
        ),
    ]
